### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by adamnejm** [iamcco/async-await.lua#1]
Please provide a license for this library.  
  
Why it's important:
>If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.  
[~Source](https://choosealicense.com/no-permission/)  
  
My favorite ones *(simple and permissive)*:  
[Unlicense](https://choosealicense.com/licenses/unlicense/) - Public domain, no conditions
[MIT](https://choosealicense.com/licenses/mit/) - License and copyright notice
  
More licenses: https://choosealicense.com/

**Comment by iamcco** [comment]
Done https://github.com/iamcco/async-await.lua/commit/2dfd9531e080a61c2b4f7c8b50c6a5498ab6da79
